config/routes.rb
Rails.application.routes.draw do
  get   '/admin_login', :to => 'login#index'
  get   '/user_login', :to => 'sign_in#index'
  resources :users
  resources :sign_in
  resources :admins

  resources :books

  resources :types

  resources :login
  root 'home#index'
  resources :books do 
    collection do
      post 'create_new_book'
    end
  end

  resources :books do 
    collection do
      post "change_type"
    end
  end


  resources :his do 
    collection do
      get 'history'
      get 'history_book'
      post 'change_type'
      get 'user'
      get 'book'
    end
  end

  resources :types do 
    collection do
      get 'index'
      get 'show'
      post "update"
    end
  end
  resources :usage do 
    collection do
      get 'index'
      get 'book'
    end
  end

  resources :home do 
    collection do
      get 'index'
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_presence_of :kod
  validates_presence_of :phone
  validates_uniqueness_of :email
  validates_uniqueness_of :phone
  validates_uniqueness_of :kod
  
  def self.authenticate(kod, password)
    admin = find_by_kod(kod)
    if admin && admin.password_hash == BCrypt::Engine.hash_secret(password, admin.password_salt)
      admin
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.search(query)
    where do 
      (firstname =~ "#{query}") |
      (kod =~ "%#{query}%")
    end   
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :type
	has_many :bookrent

	def self.search(query)
    where do 
      (name =~ "#{query}") |
      (isbn =~ "%#{query}%")
    end   
  end
end

app/models/bookrent.rb
class Bookrent < ActiveRecord::Base
	belongs_to :book
end

app/models/mne.rb
class Mne < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :book
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_presence_of :phone
  validates_uniqueness_of :email
  validates_uniqueness_of :phone
  
  def self.authenticate(email, password)
    obj = find_by_email(email)
    if obj && obj.password_hash == BCrypt::Engine.hash_secret(password, obj.password_salt)
      obj
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.search(query)
    where do 
      (firstname =~ "#{query}") |
      (kod =~ "%#{query}%")
    end   
  end
end

app/models/user_repeat_login.rb
class UserRepeatLogin < ActiveRecord::Base
end

app/models/usermenu.rb
class Usermenu < ActiveRecord::Base
end

app/controllers/his_controller.rb
class HisController < ApplicationController
  
  def user
    @m = "/his/user"
    @ids  = UserRepeatLogin.pluck(:user_id)
    @data = User.where(id: @ids).page(params[:page]).per(20)
  end
  
  def book
    @m = "/his/book"
    @ids  = Bookrent.all.pluck(:book_id)
    @data = Book.where(id: @ids).page(params[:page]).per(20)
  end
  
  def history
    @m = "/his/history"
    @bookrents = Bookrent.all.order("created_at DESC").page(params[:page]).per(20)
  end

  def history_book
    @m = "/his/history_book"
  	if params[:user_id].to_i>0
  	 	@bookrents = Bookrent.where(user_Id: params[:user_id].to_i).order("created_at DESC").page(params[:page]).per(20)
  	 else
  	 		@bookrents =  Bookrent.all.order("created_at DESC").page(params[:page]).per(20)
  	end
  	@types= Array.new

  	@types.push(value: "Хүсэлт тодорхойгүй", id:0)
  	@types.push(value: "Хүсэлт илгээгдсэн", id:1)
  	@types.push(value: "Гэрээр олгогдсон", id:2)
  	@types.push(value: "Буцаан өгсөн", id:3)
  end

  def change_type
    Bookrent.find(params[:trip][:id]).update(status:params[:trip][:status]).page(params[:page]).per(20)
    redirect_to URI.escape("/his/history_book")
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :check_logined
  before_filter :check_user_logined
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/his_helper.rb
module HisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/usage_helper.rb
module UsageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.haml
= form_for @admin do |f|
  - if @admin.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin.errors.count, "error")} prohibited this admin from being saved:"
      %ul
        - @admin.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :Код
    = f.number_field :kod, disabled: "disabled"
  .field
    = f.label :Нэр
    = f.text_field :firstname
  .field
    = f.label :Овог
    = f.text_field :lastname
  .field
    = f.label "И-мэйл"
    = f.text_field :email
  .field
    = f.label :РД
    = f.text_field :rd
  .field
    = f.label :Утас
    = f.text_field :phone
  .field
    = f.label "Утас /Гэр"
    = f.text_field :phone_home
  .actions
    = f.submit 'Хадгалах',class: "btn"

app/views/admins/edit.html.haml
.row
	.col.s12
		.col.s6
			%a.btn{:href=>"javascript:window.location.href='/admins/#{@admin.id}'"} Харах
			%a.btn{:href=>"javascript:window.location.href='/admins'"} Буцах
		.col.s6{style: "text-align:right"}
			%h5 Ажилтаны мэдээлэл засах
		
	.col.s12
		= render 'form'

app/views/admins/index.html.haml
%a.fixed-action-btn.horizontal.modal{:href => "#add_data",style:"background:transparent"}
  .btn-floating.btn-large
    %i.material-icons add

.modal.small_modal{:id=>"add_data"}
  .modal-content
    %i.material-icons.modal-close close
    .header
      %h5 Админ бүртгэх
    .content.container
      = form_for @admin, :url => {:action => "create"}, :method => "post" do |f|
        %p= f.hidden_field   :kod,value:@last_cod
        %p= f.text_field     :email,:placeholder =>"E-mail"
        %p= f.text_field     :firstname,:placeholder=>"Нэр"
        %p= f.text_field     :lastname,:placeholder =>"Овог"
        %p= f.text_field     :rd,:placeholder =>"РД"
        %p= f.text_field     :phone,:placeholder =>"Утас"
        %p= f.text_field     :phone_home,:placeholder =>"Гэрийн утас"
        %p= f.password_field :password,:placeholder =>"Нууц үг"
        %p= f.password_field :password_confirmation,:placeholder=>"Нууц үг давтах"
        %center.col.s12
          = f.submit "Хадгалъя",:class=>"btn"

.col-xs-3.col-sm-3.col-md-3
  = form_tag 'admins', method: :get do
    = text_field_tag :search, params[:search] , :value => 'хaйх ...', :onfocus => 'this.value = ""' ,:style=>"background-image: url('/assets/ic_search.png'); background-repeat: no-repeat;     background-size: 40px 30px; background-position: right;     border: 1px solid #e1e6ea; color: #c7cfd5; font-size:13px; font-family: 'Open Sans', sans-serif; width:100%; padding-left:20px "

%table
  %thead
    %tr
      %th Код
      %th Нэр
      %th Овог
      %th И-мэйл
      %th РД
      %th Утас
      %th{colspan:3}

  %tbody
    - @admins.each do |admin|
      %tr
        %td= admin.kod
        %td= admin.firstname
        %td= admin.lastname
        %td= admin.email
        %td= admin.rd
        %td= admin.phone
        %td= link_to 'Дэлгэрэнгүй харах', admin
        %td= link_to 'Засах', edit_admin_path(admin)
        %td= link_to 'Устгах', admin, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
%br
%br
=paginate @admins

app/views/admins/new.html.haml
.row
  .col.s12
    .col.s6
      %a.btn{:href=>"javascript:window.location.href='/admins'"} Буцах
    .col.s6{style: "text-align:right"}
      %h5 Ажилтан
  .col.s12
		= render 'form'

app/views/admins/show.html.haml
.row
  .col.s12
    .col.s6
      %a.btn{:href=>"javascript:window.location.href='/admins/#{@admin.id}/edit'"} Засах
      %a.btn{:href=>"javascript:window.location.href='/admins'"} Буцах
    .col.s6{style: "text-align:right"}
      %h5 Ажилтаны дэлгэрэнгүй мэдээлэл
  .col.s12
    %p#notice= notice
    %p
      %b Код:
      = @admin.kod
    %p
      %b Нэр:
      = @admin.firstname
    %p
      %b И-мэйл:
      = @admin.lastname
    %p
      %b Email:
      = @admin.email
    %p
      %b РД:
      = @admin.rd
    %p
      %b Утас:
      = @admin.phone
    %p
      %b Утас /Гэр:
      = @admin.phone_home

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title Library
		%link{:href => "/assets/icon.png/", :rel => "shortcut icon"}/
		= stylesheet_link_tag "application", params[:controller], :media => "all", 'data-turbolinks-track' => true
		= javascript_include_tag "application", params[:controller], 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		-if current_user
			%nav
				.nav-wrapper
					%a.brand-logo.right{:href => "#!",style:"top:0px"} Library
					%a.button-collapse{"data-activates" => "slide-out", :href => "#"}
						%i.material-icons menu
			%ul#slide-out.side-nav.fixed
				%li
					.userView
						.background
							%img{:src => "/assets/book.jpg"}/
						%a{:href=>"javascript:window.location.href='/admins'"}
							%img.circle{:src => "/assets/icon.png"}/
						%a{:href=>"javascript:window.location.href='/admins'"}
							%span.white-text.name #{current_user.firstname} #{current_user.lastname}
						%a{:href=>"javascript:window.location.href='/admins'"}
							%span.white-text.email #{current_user.email}
				%li
					%a{:href=>"javascript:window.location.href='/admins'"}
						%i.material-icons> cloud
						Нүүр хуудас
				
				-Usermenu.where(s:1).all.each do |menu|
					-if menu.l.to_s == @m.to_s
						%li.active
							%a{:href=>"javascript:window.location.href='#{menu.l}'"}=menu.v
					-else
						%li
							%a{:href=>"javascript:window.location.href='#{menu.l}'"}=menu.v
				
				%li
					%a{:href=>"javascript:window.location.href='/login'"}
			%main
				.flash
					-flash.each do |key, value|
						.alert{:class=>"alert-#{key}"}=value
				= yield
		-elsif system_user
			%nav
				.nav-wrapper
					%a.brand-logo.right{:href => "#!",style:"top:0px"} Library
					%a.button-collapse{"data-activates" => "slide-out", :href => "#"}
						%i.material-icons menu
			%ul#slide-out.side-nav.fixed
				%li
					.userView
						.background
							%img{:src => "/assets/book1.jpeg"}/
						%a{:href=>"javascript:window.location.href='/admins'"}
							%img.circle{:src => "/assets/icon.png"}/
						%a{:href=>"javascript:window.location.href='/admins'"}
							%span.white-text.name #{system_user.firstname} #{system_user.lastname}
						%a{:href=>"javascript:window.location.href='/admins'"}
							%span.white-text.email #{system_user.email}
				%li
					%a{:href=>"javascript:window.location.href='/books'"} Номын жагсаалт
				%li
					.divider
				%li
					%a{:href=>"javascript:window.location.href='/usage'"} Зээлэгдсэн номын мэдээлэл
		
				%li
					.divider
				%li
					%a{:href=>"javascript:window.location.href='/sign_in'"} Гарах
			%main
				.flash
					-flash.each do |key, value|
						.alert{:class=>"alert-#{key}"}=value
				= yield
		-else
			=yield