config/routes.rb
Rails.application.routes.draw do
  get   '/admin_login', :to => 'login#index'
  get   '/user_login', :to => 'sign_in#index'
  resources :users
  resources :sign_in
  resources :admins

  resources :books

  resources :types

  resources :login
  root 'home#index'
  resources :books do 
    collection do
      post 'create_new_book'
    end
  end

  resources :books do 
    collection do
      post "change_type"
    end
  end


  resources :his do 
    collection do
      get 'history'
      get 'history_book'
      post 'change_type'
      get 'user'
      get 'book'
    end
  end

  resources :types do 
    collection do
      get 'index'
      get 'show'
      post "update"
    end
  end
  resources :usage do 
    collection do
      get 'index'
      get 'book'
    end
  end

  resources :home do 
    collection do
      get 'index'
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_filter :check_logined
  before_action :set_type, only: [:show, :edit, :destroy]

  # GET /types
  # GET /types.json
  def index
    @m = "/types"
    @types = Type.all
    @type = Type.new
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @m = "/types"
  end

  # GET /types/new
  def new
    @m = "/types"
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
    @m = "/types"
  end

  def create
    @obj = Type.new(type_params)
    if !@obj.save
      @obj = Type.all.page(params[:page]).per(20)
    end
    redirect_to URI.escape("/types")
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    Type.find(params[:type][:id]).update(title: params[:type][:title])
    redirect_to URI.escape("/types")
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:title)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.haml
= form_for @type do |f|
  - if @type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@type.errors.count, "error")} prohibited this type from being saved:"
      %ul
        - @type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/types/edit.html.haml
%h1 Editing type

= render 'form'

= link_to 'Show', @type
\|
= link_to 'Back', types_path

app/views/types/index.html.haml
.fixed-action-btn.horizontal.modal-trigger{:href => "#add_data",:style=>"color:#767676; "}
  %a.btn-floating.btn-large.green
    %i.material-icons add

.modal.small_modal{:id=>"add_data"}
  .modal-content
    %i.material-icons.modal-close close
    .header
      %h5 Админ бүртгэх
    .content.container
      = form_for @type, :url => {:action => "create"}, :method => "post" do |f|
        %p= f.text_field :title
        %center.col.s12
          = f.submit "Хадгалъя",:class=>"btn"

%table
  %thead
    %tr
      %th Утга
      %th{colspan:2}

  %tbody
    - @types.each do |type|
      .modal.small_modal{:id=>"ss#{type.id}"}
        .modal-content
          %i.material-icons.modal-close close
          .header
            %h5 Админ бүртгэх
          .content.container
            = form_for @type, :url => {controller: "types",action: "update"}, :method => "post" do |f|
              = f.hidden_field :id,:value=>type.id
              %p= f.text_field :title,:value=>type.title
              %center.col.s12
                = f.submit "Хадгалъя",:class=>"btn"
      %tr
        %td= type.title
        %td
          %a.modal-trigger{:href => "#ss#{type.id}",:style=>"color:#767676; "} Засах

        %td= link_to 'Устгах', type, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/types/new.html.haml
%h1 New type

= render 'form'

= link_to 'Back', types_path

app/views/types/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @type.title

= link_to 'Edit', edit_type_path(@type)
\|
= link_to 'Back', types_path